### PR TITLE
Custom formatting options and updated devDependencies

### PR DESCRIPTION
**Pull request by epd**
Hey there! Stumbled across this module today and loved the simplicity of the middleware compared to many others. I decided to take it upon myself to extend this a little bit and offer custom tokens to be passed in to have better control over the output that is sent to Winston.

I've updated the `README.md` as well as (re-)written tests, as some of the dependencies were very old. Would love to get this merged in!

Let me know if you have any questions/concerns.

Evan

### CODE REVIEW

**Comment by wolfeidau** [comment]
Yeah looks awesome.

I haven't touched this in ages as you can probably tell.

If you plan to use it I am happy to add you as a contributor here and in npm.

**Comment by wolfeidau** [comment]
Published in npm.

**Comment by epd** [comment]
@wolfeidau - Thanks! Would love to help maintain this.

**Comment by wolfeidau** [comment]
@evNN Do you have a login for npm? if so what is it :)

I have added you as a collaborator.

**Comment by epd** [comment]
@wolfeidau - username is "evandudla".

**Comment by wolfeidau** [comment]
This is how i normally publish npm modules.

Update the version using `npm`, you can pass either major, minor or patch depending on which number you want to increment, in this case i am marking this as a patch.

```
winston-request-logger (master)]$ npm version patch
v1.0.1
```

Push to github with the tag created by `npm`.

```
winston-request-logger (master)]$ git push origin master --tags
Counting objects: 6, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (4/4), done.
Writing objects: 100% (4/4), 405 bytes | 0 bytes/s, done.
Total 4 (delta 2), reused 0 (delta 0)
To https://github.com/wolfeidau/winston-request-logger
   754207b..9fda811  master -> master
 * [new tag]         v1.0.1 -> v1.0.1
```

Wait for travis to pass... then :ship: 

```
winston-request-logger (master)]$ npm publish
npm http PUT https://registry.npmjs.org/winston-request-logger
npm http 409 https://registry.npmjs.org/winston-request-logger
npm http GET https://registry.npmjs.org/winston-request-logger
npm http 200 https://registry.npmjs.org/winston-request-logger
npm http PUT https://registry.npmjs.org/winston-request-logger
npm http 201 https://registry.npmjs.org/winston-request-logger
+ winston-request-logger@1.0.1
```

Hope that helps.

**Comment by epd** [comment]
Awesome, thanks for this!

**Comment by wolfeidau** [comment]
Done https://npmjs.org/~evandudla

Make sure you add your name to the `README.md` something like this https://github.com/rvagg/learnyounode#contributors

**Pull request merged**
